stages:
  - build
  - deploy

steps:
  Package:
    type: build
    title: Package frontend app
    stage: build
    commands:
      - npm run package
      - cd .microtica
      - npm install
      - npm run build
      - npm prune --production
      - cd functions/deployment && npm run package
    artifacts:
      files:
        package_zip: ./.microtica/
        schema_json: ./.microtica/schema.json
    cache: false   

  DeployComponent:
    title: Trigger a deployment for an environment resource
    type: deploy
    target: environment
    stage: deploy
    env_id: "{{ENV_ID}}"
    partial:
        create_missing_resources: true
        resource_version_overrides:
          {{AppName}}: "{{MIC_PIPELINE_EXECUTION_ID}}"